/**
 * DADOS INICIAIS DE DEMONSTRAÇÃO - SME LUZIÂNIA
 * Permite que o sistema funcione 100% offline em Modo Demo / Híbrido.
 */

export const INITIAL_ESCOLAS = [
  {
    "id": "e-52101894",
    "nome": "1ª Escola Municipal de Tempo Integral Laudimirio de Jesus Tormin",
    "codigo_inep": "52101894",
    "endereco": "RUA 81, 376 AREA ESPECIAL. PARQUE ESTRELA DALVA V. - Área Especial - PARQUE ESTRELA DALVA V - LUZIÂNIA/GO - CEP: 72.806-040",
    "logradouro": "RUA 81, 376 AREA ESPECIAL. PARQUE ESTRELA DALVA V.",
    "complemento": "Área Especial",
    "bairro": "PARQUE ESTRELA DALVA V",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.806-040",
    "latitude": "-16.262069",
    "longitude": "-47.928154",
    "contato": "(61) 99122-3502",
    "email": "laudimiriojesus@educacao.luziania.go.gov.br",
    "gestor_nome": "062.954.041-11",
    "gestor_cpf": "andrehdr@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "ELSA DE ALMEIDA DE OLIVEIRA",
    "secretario_nome": "142.916.493-04",
    "secretario_cpf": "elsadealmeida2008@hotmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "ANA PAULA OLIVEIRA DA SILVA",
    "classificacao": "INTEGRAL",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "2016",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52075125",
    "nome": "1ª Escola Polo Municipal Rural Realino Caixeta",
    "codigo_inep": "52075125",
    "endereco": "Área Rural - DISTRITO DE LUZIANIA - ZONAS RURAL - LUZIÂNIA/GO - CEP: 72.859-899",
    "logradouro": "Área Rural",
    "complemento": "DISTRITO DE LUZIANIA",
    "bairro": "ZONAS RURAL",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.859-899",
    "latitude": "-16.81748",
    "longitude": "-48.03078",
    "contato": "(61) 99992-9014",
    "email": "realinocaixeta@educacao.luziania.go.gov.br",
    "gestor_nome": "780.549.741-91",
    "gestor_cpf": "lucienepereiratiagodarocha@gmail.com",
    "gestor_email": "(61) 99992-9014",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "RURAL",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "2003",
    "rede": "Municipal",
    "tipo_localizacao": "Rural",
    "turnos": "Matutino/Manhã",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52048314",
    "nome": "2ª Escola Polo Municipal Rural Samambaia Darcy Ribeiro",
    "codigo_inep": "52048314",
    "endereco": "GO 040 KM 48, FAZENDA SAMAMBAIA. ZONA RURAL. - ZONAS RURAL - LUZIÂNIA/GO - CEP: 72.813-970",
    "logradouro": "GO 040 KM 48, FAZENDA SAMAMBAIA. ZONA RURAL.",
    "complemento": "",
    "bairro": "ZONAS RURAL",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.813-970",
    "latitude": "-16.464065",
    "longitude": "-48.214510",
    "contato": "(61) 99818-5348",
    "email": "darcyribeiro@educacao.luziania.go.gov.br",
    "gestor_nome": "849.481.321-87",
    "gestor_cpf": "fernandamartinsluziania@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "RURAL",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Rural",
    "turnos": "Matutino/Manhã",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52048160",
    "nome": "3ª Escola Polo Municipal Rural Araras Nair Tiecher",
    "codigo_inep": "52048160",
    "endereco": "AREA RURAL, AREA RURAL DE LUZIANIA. - ZONAS RURAL - LUZIÂNIA/GO - CEP: 72.859-899",
    "logradouro": "AREA RURAL, AREA RURAL DE LUZIANIA.",
    "complemento": "",
    "bairro": "ZONAS RURAL",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.859-899",
    "latitude": "-16.515551",
    "longitude": "-47.939555",
    "contato": "(61) 99603-8641",
    "email": "nairtiecher@educacao.luziania.go.gov.br",
    "gestor_nome": "869.081.461-20",
    "gestor_cpf": "cirleimeireles2010@hotmail.com",
    "gestor_email": "(61) 99187-5110",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "KATIA BRAZ DE QUEIROZ",
    "secretario_nome": "901.158.641-72",
    "secretario_cpf": "katiabrazqueiroz@gmail.com",
    "secretario_email": "(61) 99675-6226",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "RURAL",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Rural",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52070646",
    "nome": "4ª Escola Polo Municipal Rural dos Americanos",
    "codigo_inep": "52070646",
    "endereco": "Quadra 39 - MANSOES DE RECREIO ESTRELA DALVA VI - LUZIÂNIA/GO - CEP: 72.809-195",
    "logradouro": "Quadra 39",
    "complemento": "",
    "bairro": "MANSOES DE RECREIO ESTRELA DALVA VI",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.809-195",
    "latitude": "-16.347311",
    "longitude": "-47.914460",
    "contato": "(61) 99914-4033",
    "email": "americanos@educacao.luziania.go.gov.br",
    "gestor_nome": "993.744.711-91",
    "gestor_cpf": "geisianeribeiro1982@gmail.com",
    "gestor_email": "(61) 99680-3337",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "MAGNA SIMEIA DA SILVA FERREIRA",
    "secretario_nome": "983.053.791-91",
    "secretario_cpf": "simeia.magna34@gmail.com",
    "secretario_email": "(61) 99193-6106",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "INTEGRAL",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "2025",
    "rede": "Municipal",
    "tipo_localizacao": "Rural",
    "turnos": "Matutino/Manhã|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52047873",
    "nome": "5ª Escola Polo Municipal Rural Hortencia Maria Felacio",
    "codigo_inep": "52047873",
    "endereco": "AREA ESPECIAL, BR 040 KM 38, QUADRA 143 - JARDIM BANDEIRENTE - LUZIÂNIA/GO - CEP: 72.833-283",
    "logradouro": "AREA ESPECIAL, BR 040 KM 38, QUADRA 143",
    "complemento": "",
    "bairro": "JARDIM BANDEIRENTE",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.833-283",
    "latitude": "-16.268851",
    "longitude": "-47.857289",
    "contato": "(61) 99555-2305",
    "email": "hortenciamaria@educacao.luziania.go.gov.br",
    "gestor_nome": "051.918.321-59",
    "gestor_cpf": "deividpereira.df@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "RURAL",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Rural",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52048608",
    "nome": "6ª Escola Polo Municipal Rural Jose Rodrigues dos Reis",
    "codigo_inep": "52048608",
    "endereco": "GO 010, KM 08, COMERCIO LOCAL, TRES VENDAS - ZONAS RURAL - LUZIÂNIA/GO - CEP: 72.800-010",
    "logradouro": "GO 010, KM 08, COMERCIO LOCAL, TRES VENDAS",
    "complemento": "",
    "bairro": "ZONAS RURAL",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.800-010",
    "latitude": "-16.313552",
    "longitude": "-48.014726",
    "contato": "(61) 99660-3745",
    "email": "rodriguesreis@educacao.luziania.go.gov.br",
    "gestor_nome": "014.117.251-74",
    "gestor_cpf": "claudia.vort@gmail.com",
    "gestor_email": "(61) 99289-6737",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "FRANCISCO CLERTON RODRIGUES SENA",
    "secretario_nome": "698.908.381-68",
    "secretario_cpf": "franciscoclertonrodriguessena@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "RURAL",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Rural",
    "turnos": "Matutino/Manhã",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52047814",
    "nome": "CMEB Alda Vieira de Souza Mingone I",
    "codigo_inep": "52047814",
    "endereco": "QUADRA 32, PRACA 01. PARQUE INDUSTRIAL MINGONE. - PARQUE INDUSTRIAL MINGONE I - LUZIÂNIA/GO - CEP: 72.855-032",
    "logradouro": "QUADRA 32, PRACA 01. PARQUE INDUSTRIAL MINGONE.",
    "complemento": "",
    "bairro": "PARQUE INDUSTRIAL MINGONE I",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.855-032",
    "latitude": "-16.159383",
    "longitude": "-47.938367",
    "contato": "(61) 3623-7595",
    "email": "mingone1@educacao.luziania.go.gov.br",
    "gestor_nome": "845.499.551-04",
    "gestor_cpf": "gilzabonfim22@gmail.com",
    "gestor_email": "(61) 99812-4664",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52098249",
    "nome": "CMEB Alzira Elvira Xavier",
    "codigo_inep": "52098249",
    "endereco": "RUA PARANOA, 12 A 17 QUADRA 02. JARDIM FLAMBOYANT. - JARDIM FLAMBOYANT - LUZIÂNIA/GO - CEP: 72.852-575",
    "logradouro": "RUA PARANOA, 12 A 17 QUADRA 02. JARDIM FLAMBOYANT.",
    "complemento": "",
    "bairro": "JARDIM FLAMBOYANT",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.852-575",
    "latitude": "-16.116239",
    "longitude": "-47.965434",
    "contato": "(61) 99108-2086",
    "email": "flamboyant@educacao.luziania.go.gov.br",
    "gestor_nome": "706.193.101-97",
    "gestor_cpf": "borgeselza064@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "2007",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52047610",
    "nome": "CMEB André Rochais",
    "codigo_inep": "52047610",
    "endereco": "AVENIDA SARA KUBITSCHEK, PARQUE JK. - PARQUE JK - LUZIÂNIA/GO - CEP: 72.815-450",
    "logradouro": "AVENIDA SARA KUBITSCHEK, PARQUE JK.",
    "complemento": "",
    "bairro": "PARQUE JK",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.815-450",
    "latitude": "-16.240181",
    "longitude": "-47.943029",
    "contato": "(61) 99282-1548",
    "email": "andrerochais@educacao.luziania.go.gov.br",
    "gestor_nome": "003.273.721-17",
    "gestor_cpf": "thiagoquadro83@gmail.com",
    "gestor_email": "(61) 98488-8439",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "MARIA EDUARDA PINHEIRO PERES DA SILVA",
    "secretario_nome": "709.972.481-90",
    "secretario_cpf": "mariaeduarda98699833@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52047679",
    "nome": "CMEB Carlos Alberto Brandao Ferreira",
    "codigo_inep": "52047679",
    "endereco": "RUA ELISEU DE MELO - SETOR FUMAL - LUZIÂNIA/GO - CEP: 72.801-570",
    "logradouro": "RUA ELISEU DE MELO",
    "complemento": "",
    "bairro": "SETOR FUMAL",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.801-570",
    "latitude": "-16.267494",
    "longitude": "-47.954906",
    "contato": "(61) 99277-5232",
    "email": "carlosalberto@educacao.luziania.go.gov.br",
    "gestor_nome": "861.701.981-68",
    "gestor_cpf": "coordenacaofumal@outlook.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "2025",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52088758",
    "nome": "CMEB Cora Coralina",
    "codigo_inep": "52088758",
    "endereco": "Rua Luziânia - QUADRA CM - JARDIM DO INGA - LUZIÂNIA/GO - CEP: 72.850-130",
    "logradouro": "Rua Luziânia",
    "complemento": "QUADRA CM",
    "bairro": "JARDIM DO INGA",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.850-130",
    "latitude": "-16.142516",
    "longitude": "-47.964025",
    "contato": "(61) 99282-1675",
    "email": "coracoralina@educacao.luziania.go.gov.br",
    "gestor_nome": "707.288.101-82",
    "gestor_cpf": "monicaprofluz@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "LUCELIA CORREIA GUIMARAES",
    "secretario_nome": "715.417.051-49",
    "secretario_cpf": "lulucguima@gmail.com",
    "secretario_email": "(61) 99273-1295",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52048527",
    "nome": "CMEB Dom Agostinho",
    "codigo_inep": "52048527",
    "endereco": "Rua Senhor do Bonfim - QD. 05, AREA ESP. - PARQUE CRUZEIRO DO SUL - LUZIÂNIA/GO - CEP: 72.851-170",
    "logradouro": "Rua Senhor do Bonfim",
    "complemento": "QD. 05, AREA ESP.",
    "bairro": "PARQUE CRUZEIRO DO SUL",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.851-170",
    "latitude": "-16.139600",
    "longitude": "-47.935946",
    "contato": "(61) 98603-3116",
    "email": "domagostinho@educacao.luziania.go.gov.br",
    "gestor_nome": "001.047.641-55",
    "gestor_cpf": "prof.riccardo@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52047890",
    "nome": "CMEB Dom Bosco",
    "codigo_inep": "52047890",
    "endereco": "RUA 21, QUADRA 101 AE 04. PARQUE ALVORADA I. - PARQUE ALVORADA I - LUZIÂNIA/GO - CEP: 72.836-340",
    "logradouro": "RUA 21, QUADRA 101 AE 04. PARQUE ALVORADA I.",
    "complemento": "",
    "bairro": "PARQUE ALVORADA I",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.836-340",
    "latitude": "-16.210969",
    "longitude": "-47.928974",
    "contato": "(61) 99279-0744",
    "email": "dombosco@educacao.luziania.go.gov.br",
    "gestor_nome": "041.708.085-92",
    "gestor_cpf": "msafpreta@gmail.com",
    "gestor_email": "(61) 9243-9974",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "RODRIGO VALERIO DE BARROS",
    "secretario_nome": "856.210.301-25",
    "secretario_cpf": "rvb.rodrigo@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52047717",
    "nome": "CMEB Dona Geni da Costa Afonso",
    "codigo_inep": "52047717",
    "endereco": "QUADRA QUADRA 256, LOTE B. PARQUE ESTRELA DALVA IX. - PARQUE ESTRELA DALVA IX - LUZIÂNIA/GO - CEP: 72.853-256",
    "logradouro": "QUADRA QUADRA 256, LOTE B. PARQUE ESTRELA DALVA IX.",
    "complemento": "",
    "bairro": "PARQUE ESTRELA DALVA IX",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.853-256",
    "latitude": "-16.155823",
    "longitude": "-47.957823",
    "contato": "(61) 99281-7348",
    "email": "donageni@educacao.luziania.go.gov.br",
    "gestor_nome": "032.272.921-14",
    "gestor_cpf": "daulyson@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "GISLENE DA SILVA CAVALCANTE",
    "secretario_nome": "029.551.321-79",
    "secretario_cpf": "gislene_@outlook.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Noturno/Noite",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52047768",
    "nome": "CMEB Dona Nina",
    "codigo_inep": "52047768",
    "endereco": "RUA 5, QUADRA 44 LOTE 20 - JARDIM PLANALTO - LUZIÂNIA/GO - CEP: 72.851-633",
    "logradouro": "RUA 5, QUADRA 44 LOTE 20",
    "complemento": "",
    "bairro": "JARDIM PLANALTO",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.851-633",
    "latitude": "-16.130630",
    "longitude": "-47.949377",
    "contato": "(61) 99694-7956",
    "email": "donanina@educacao.luziania.go.gov.br",
    "gestor_nome": "888.334.881-87",
    "gestor_cpf": "arqeduardo@live.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "TONHÃO NUNES DE SOUZA",
    "secretario_nome": "059.371.731-71",
    "secretario_cpf": "nunestonhao.contato@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52092020",
    "nome": "CMEB Eleuza Aparecida de Paiva Neto",
    "codigo_inep": "52092020",
    "endereco": "Rua Brasil - Quadra 73 Lote 43 - JARDIM DO INGA - LUZIÂNIA/GO - CEP: 72.850-270",
    "logradouro": "Rua Brasil",
    "complemento": "Quadra 73 Lote 43",
    "bairro": "JARDIM DO INGA",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.850-270",
    "latitude": "-16.144726",
    "longitude": "-47.956760",
    "contato": "(61) 99312-3135",
    "email": "eleuzaaparecida@educacao.luziania.go.gov.br",
    "gestor_nome": "701.659.551-04",
    "gestor_cpf": "g.olliveira@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "RANIELE LIMA DA SILVA",
    "secretario_nome": "062.225.471-50",
    "secretario_cpf": "limaraniele570@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52111741",
    "nome": "CMEB Espirita Gilson de Mendonça Henriques",
    "codigo_inep": "52111741",
    "endereco": "Rua A - QUADRA 26 LOTE 5 - SETOR NORTE SERRINHA - LUZIÂNIA/GO - CEP: 72.815-770",
    "logradouro": "Rua A",
    "complemento": "QUADRA 26 LOTE 5",
    "bairro": "SETOR NORTE SERRINHA",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.815-770",
    "latitude": "-16.232210",
    "longitude": "-47.946080",
    "contato": "(61) 99288-0750",
    "email": "gilsonmendonca@educacao.luziania.go.gov.br",
    "gestor_nome": "897.779.301-78",
    "gestor_cpf": "patriciosever.ptr@gmail.com",
    "gestor_email": "(61) 99999-3902",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "2000",
    "rede": "Privada",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52047709",
    "nome": "CMEB Francisco Vieira Lins Naldo",
    "codigo_inep": "52047709",
    "endereco": "RUA 22 - AREA ESPECIAL - PARQUE ESTRELA DALVA IV - LUZIÂNIA/GO - CEP: 72.821-210",
    "logradouro": "RUA 22",
    "complemento": "AREA ESPECIAL",
    "bairro": "PARQUE ESTRELA DALVA IV",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.821-210",
    "latitude": "-16.259907",
    "longitude": "-47.912727",
    "contato": "(61) 99609-6644",
    "email": "dalva4@educacao.luziania.go.gov.br",
    "gestor_nome": "885.225.201-00",
    "gestor_cpf": "marilisboanoronha@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "DHENIS BRITO OLIVEIRA",
    "secretario_nome": "708.841.931-95",
    "secretario_cpf": "britodhenis29@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52076814",
    "nome": "CMEB Getulio Jose da Costa",
    "codigo_inep": "52076814",
    "endereco": "Quadra 68 - PARQUE ESTRELA DALVA IX - LUZIÂNIA/GO - CEP: 72.853-068",
    "logradouro": "Quadra 68",
    "complemento": "",
    "bairro": "PARQUE ESTRELA DALVA IX",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.853-068",
    "latitude": "-16.157050",
    "longitude": "-47.946875",
    "contato": "(61) 99286-8599",
    "email": "getuliojose@educacao.luziania.go.gov.br",
    "gestor_nome": "056.118.391-00",
    "gestor_cpf": "camilafranca090@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "RAIZA LOPES DA SILVA",
    "secretario_nome": "705.990.521-98",
    "secretario_cpf": "lopesraiza2014@gmail.com",
    "secretario_email": "(61) 99254-2500",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "BIANCA SANTOS DUTHEVICZ",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52075141",
    "nome": "CMEB Kelly Susan Santos",
    "codigo_inep": "52075141",
    "endereco": "PRAÇA 04 AVENIDA 5 PARQUE MINGONE II LUZIÂNIA, GO - AREA ESPECIAL - PARQUE INDUSTRIAL MINGONE II - LUZIÂNIA/GO - CEP: 72.855-245",
    "logradouro": "PRAÇA 04 AVENIDA 5 PARQUE MINGONE II LUZIÂNIA, GO",
    "complemento": "AREA ESPECIAL",
    "bairro": "PARQUE INDUSTRIAL MINGONE II",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.855-245",
    "latitude": "-16.145459",
    "longitude": "-47.939343",
    "contato": "(61) 99278-9818",
    "email": "escolakellysusansantos@gmail.com",
    "gestor_nome": "017.286.341-48",
    "gestor_cpf": "profeleonardodasilva@gmail.com",
    "gestor_email": "(61) 99181-9892",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "JESSICA PEIXOTO NASCIMENTO ALVES",
    "secretario_nome": "037.419.691-50",
    "secretario_cpf": "gaditafiel@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52070557",
    "nome": "CMEB Laudimiro Roriz",
    "codigo_inep": "52070557",
    "endereco": "Quadra 171 - MANSOES DE RECREIO ESTRELA DALVA VIII - LUZIÂNIA/GO - CEP: 72.859-171",
    "logradouro": "Quadra 171",
    "complemento": "",
    "bairro": "MANSOES DE RECREIO ESTRELA DALVA VIII",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.859-171",
    "latitude": "-16.162301",
    "longitude": "-47.995286",
    "contato": "(61) 98300-8424",
    "email": "laudimirororiz@educacao.luziania.go.gov.br",
    "gestor_nome": "835.941.321-53",
    "gestor_cpf": "edmarcacau@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52096874",
    "nome": "CMEB Manoel Fernandes Vieira",
    "codigo_inep": "52096874",
    "endereco": "RUA 120 - QUADRA 340 - PARQUE ESTRELA DALVA IX - LUZIÂNIA/GO - CEP: 72.853-340",
    "logradouro": "RUA 120",
    "complemento": "QUADRA 340",
    "bairro": "PARQUE ESTRELA DALVA IX",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.853-340",
    "latitude": "-16.157194",
    "longitude": "-47.962602",
    "contato": "(61) 99811-3423",
    "email": "manoelfernandes@educacao.luziania.go.gov.br",
    "gestor_nome": "016.376.941-99",
    "gestor_cpf": "daniel.borges31@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PEDRO NATHAN DA SILVA PEREIRA",
    "secretario_nome": "086.367.161-60",
    "secretario_cpf": "silvamnathan720@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "CYNTHIA THAYCI RODRIGUES SAMPAIO DA SILVA",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52048438",
    "nome": "CMEB Marcilio Dias",
    "codigo_inep": "52048438",
    "endereco": "Quadra 607 - 607 JARDIM DO INGA - PARQUE ESTRELA DALVA X - LUZIÂNIA/GO - CEP: 72.856-607",
    "logradouro": "Quadra 607",
    "complemento": "607 JARDIM DO INGA",
    "bairro": "PARQUE ESTRELA DALVA X",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.856-607",
    "latitude": "-16.172227",
    "longitude": "-47.960959",
    "contato": "(61) 99654-8140",
    "email": "marciliodias@educacao.luziania.go.gov.br",
    "gestor_nome": "785.370.021-00",
    "gestor_cpf": "elizandragramacho@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "INTEGRAL",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52098222",
    "nome": "CMEB Maria Lucinda Leite",
    "codigo_inep": "52098222",
    "endereco": "RUA NOSSA SENHORA DO ROSARIO - DISTRITO INDUSTRIAL DE LUZIANIA (DIAL) - LUZIÂNIA/GO - CEP: 72.832-033",
    "logradouro": "RUA NOSSA SENHORA DO ROSARIO",
    "complemento": "",
    "bairro": "DISTRITO INDUSTRIAL DE LUZIANIA (DIAL)",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.832-033",
    "latitude": "-16.211545",
    "longitude": "-47.869026",
    "contato": "(61) 99638-2145",
    "email": "marialucinda@educacao.luziania.go.gov.br",
    "gestor_nome": "599.875.451-49",
    "gestor_cpf": "ednafarias01@gmail.com",
    "gestor_email": "(61) 99638-2145",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "LEONARDO DE OLIVEIRA ALCANTARA FILHO",
    "secretario_nome": "709.762.881-25",
    "secretario_cpf": "leonardodealcantara911@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "INTEGRAL",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52048853",
    "nome": "CMEB Maria Vera Lúcia de Oliveira",
    "codigo_inep": "52048853",
    "endereco": "AVENIDA ALAMEDA OSFAYA - S/N AREA ESPECIAL - OSFAYA - LUZIÂNIA/GO - CEP: 72.855-647",
    "logradouro": "AVENIDA ALAMEDA OSFAYA",
    "complemento": "S/N AREA ESPECIAL",
    "bairro": "OSFAYA",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.855-647",
    "latitude": "-16.172349",
    "longitude": "-47.921593",
    "contato": "(61) 99278-5956",
    "email": "osfaya@educacao.luziania.go.gov.br",
    "gestor_nome": "817.265.031-00",
    "gestor_cpf": "soniaemanoel15@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "ANDREA DE SOUZA FERREIRA",
    "secretario_nome": "516.706.581-04",
    "secretario_cpf": "andreasworkbr@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52047156",
    "nome": "CMEB Maria de Nondas",
    "codigo_inep": "52047156",
    "endereco": "RUA CRISTALINA QUADRA 18, ENGENHEIRO JOFRE PARADA. - AREA ESPECIAL - ENGENHEIRO JOFRE PARADA - LUZIÂNIA/GO - CEP: 72.811-300",
    "logradouro": "RUA CRISTALINA QUADRA 18, ENGENHEIRO JOFRE PARADA.",
    "complemento": "AREA ESPECIAL",
    "bairro": "ENGENHEIRO JOFRE PARADA",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.811-300",
    "latitude": "-16.2492375",
    "longitude": "-47.9646709",
    "contato": "(61) 99281-0789",
    "email": "caic@educacao.luziania.go.gov.br",
    "gestor_nome": "017.565.581-24",
    "gestor_cpf": "franciscoeverton@hotmail.com",
    "gestor_email": "(61) 98168-7164",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "LUIZA MARTINS DE OLIVEIRA",
    "secretario_nome": "586.605.261-04",
    "secretario_cpf": "luizamartins09@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "INTEGRAL",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "2025",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52047822",
    "nome": "CMEB Natalia Aparecida Louzada Alves",
    "codigo_inep": "52047822",
    "endereco": "AVENIDA 3 PRACA 3 AREA ESPECIAL, 3 PARQUE INDUSTRIAL MINGONE. - PARQUE INDUSTRIAL MINGONE - LUZIÂNIA/GO - CEP: 72.855-003",
    "logradouro": "AVENIDA 3 PRACA 3 AREA ESPECIAL, 3 PARQUE INDUSTRIAL MINGONE.",
    "complemento": "",
    "bairro": "PARQUE INDUSTRIAL MINGONE",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.855-003",
    "latitude": "-16.151858",
    "longitude": "-47.933686",
    "contato": "(61) 99811-3423",
    "email": "mingone2@educacao.luziania.go.gov.br",
    "gestor_nome": "937.977.531-87",
    "gestor_cpf": "phabiolasouza@yahoo.com.br",
    "gestor_email": "(61) 99200-8283",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Noturno/Noite",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52048802",
    "nome": "CMEB Palhoça Professora Edinir Celeste Roriz Lima",
    "codigo_inep": "52048802",
    "endereco": "Rua Maria Helena Cardoso - Area Especial - PARQUE ESTRELA DALVA III - LUZIÂNIA/GO - CEP: 72.831-060",
    "logradouro": "Rua Maria Helena Cardoso",
    "complemento": "Area Especial",
    "bairro": "PARQUE ESTRELA DALVA III",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.831-060",
    "latitude": "-16.245165",
    "longitude": "-47.902898",
    "contato": "(61) 99275-4293",
    "email": "edinirceleste@educacao.luziania.go.gov.br",
    "gestor_nome": "977.143.301-63",
    "gestor_cpf": "alessandra-rabelo@hotmail.com",
    "gestor_email": "(61) 99321-9377",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "MARIA ISABEL DE FARIA MATOS",
    "secretario_nome": "431.389.691-00",
    "secretario_cpf": "misabel.f.matos@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "2024",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52069087",
    "nome": "CMEB Professor Belim",
    "codigo_inep": "52069087",
    "endereco": "Avenida Doutor Paulino Lobo Filho - SETOR NORTE MARAVILHA - LUZIÂNIA/GO - CEP: 72.812-690",
    "logradouro": "Avenida Doutor Paulino Lobo Filho",
    "complemento": "",
    "bairro": "SETOR NORTE MARAVILHA",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.812-690",
    "latitude": "-16.240688",
    "longitude": "-47.957998",
    "contato": "(61) 99836-1226",
    "email": "belim@educacao.luziania.go.gov.br",
    "gestor_nome": "812.011.091-91",
    "gestor_cpf": "marlidias1020@gmail.com",
    "gestor_email": "(61) 99836-1226",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "ESPECIAL",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52048519",
    "nome": "CMEB Professor Ismar Goncalves",
    "codigo_inep": "52048519",
    "endereco": "Rua 30 - QD 28, AREA ESPECIAL - SETOR MANDU II - LUZIÂNIA/GO - CEP: 72.814-680",
    "logradouro": "Rua 30",
    "complemento": "QD 28, AREA ESPECIAL",
    "bairro": "SETOR MANDU II",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.814-680",
    "latitude": "-16.245654",
    "longitude": "-47.926669",
    "contato": "(61) 99275-8786",
    "email": "ismargoncalves@educacao.luziania.go.gov.br",
    "gestor_nome": "577.358.241-49",
    "gestor_cpf": "luciane.aroriz@gmail.com",
    "gestor_email": "(61) 99277-9847",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "RIZIA MARA RORIZ",
    "secretario_nome": "997.954.851-72",
    "secretario_cpf": "rorizrizia@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52048829",
    "nome": "CMEB Professor Joaquim Gilberto",
    "codigo_inep": "52048829",
    "endereco": "Rua 09 de Julho - JARDIM DO INGA - LUZIÂNIA/GO - CEP: 72.850-240",
    "logradouro": "Rua 09 de Julho",
    "complemento": "",
    "bairro": "JARDIM DO INGA",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.850-240",
    "latitude": "-16.144747",
    "longitude": "-47.954121",
    "contato": "(61) 99277-1695",
    "email": "joaquimgilberto@educacao.luziania.go.gov.br",
    "gestor_nome": "027.251.351-25",
    "gestor_cpf": "pdob.16@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "JOSE ARIEL LUCIO DE OLIVEIRA",
    "secretario_nome": "512.261.891-72",
    "secretario_cpf": "oliveirariel4@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "LORENNA MARTINS DE CASTRO",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52048586",
    "nome": "CMEB Professor Sebastiao Machado de Araujo",
    "codigo_inep": "52048586",
    "endereco": "Rua José de Melo - CENTRO - CENTRO - LUZIÂNIA/GO - CEP: 72.800-220",
    "logradouro": "Rua José de Melo",
    "complemento": "CENTRO",
    "bairro": "CENTRO",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.800-220",
    "latitude": "-16.259062",
    "longitude": "-47.949932",
    "contato": "(61) 99532-2285",
    "email": "sebastiaomachado@educacao.luziania.go.gov.br",
    "gestor_nome": "726.003.061-53",
    "gestor_cpf": "gutthos16@gmail.com",
    "gestor_email": "(61) 98345-9248",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "NÍVIA VÂNIA DA CUNHA",
    "secretario_nome": "617.509.131-00",
    "secretario_cpf": "niviavania75@gmail.com",
    "secretario_email": "(61) 99226-1790",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "INTEGRAL",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52094090",
    "nome": "CMEB Professora Ana Reis Meireles Dona Tizinha Creja",
    "codigo_inep": "52094090",
    "endereco": "Av. Ézio Carneiro, nº 275 - SETOR AEROPORTO - LUZIÂNIA/GO - CEP: 72.801-060",
    "logradouro": "Av. Ézio Carneiro, nº 275",
    "complemento": "",
    "bairro": "SETOR AEROPORTO",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.801-060",
    "latitude": "-16.252394",
    "longitude": "-47.930003",
    "contato": "(61) 99633-2225",
    "email": "anareis@educacao.luziania.go.gov.br",
    "gestor_nome": "470.445.941-15",
    "gestor_cpf": "juliom.saavedra@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "EJA",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Noturno/Noite",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52070573",
    "nome": "CMEB Professora Eva Marra Rocha",
    "codigo_inep": "52070573",
    "endereco": "Rua Pompéia - JARDIM ZULEIKA - LUZIÂNIA/GO - CEP: 72.850-560",
    "logradouro": "Rua Pompéia",
    "complemento": "",
    "bairro": "JARDIM ZULEIKA",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.850-560",
    "latitude": "-16.131779",
    "longitude": "-47.968778",
    "contato": "(61) 99275-7639",
    "email": "evamarra@educacao.luziania.go.gov.br",
    "gestor_nome": "830.871.501-00",
    "gestor_cpf": "guilhermecgs04@gmail.com",
    "gestor_email": "(61) 98225-4628|(61) 99135-0277|(61) 99549-7090",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "CELIA REGINA DA SILVA",
    "secretario_nome": "017.942.447-51",
    "secretario_cpf": "celia_rslv@hotmail.com",
    "secretario_email": "(61) 98504-2433",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52047750",
    "nome": "CMEB Professora Geralda Divina Lopes Neto",
    "codigo_inep": "52047750",
    "endereco": "RUA 03 QUADRA 18 LOTES 23/29, 23/29 PARQUE ESTRELA DALVA VII. - PARQUE ESTRELA DALVA VII - LUZIÂNIA/GO - CEP: 72.830-040",
    "logradouro": "RUA 03 QUADRA 18 LOTES 23/29, 23/29 PARQUE ESTRELA DALVA VII.",
    "complemento": "",
    "bairro": "PARQUE ESTRELA DALVA VII",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.830-040",
    "latitude": "-16.245502",
    "longitude": "-47.915985",
    "contato": "(61) 99629-4979",
    "email": "dalva7@educacao.luziania.go.gov.br",
    "gestor_nome": "020.542.281-09",
    "gestor_cpf": "professoracristyna@gmail.com",
    "gestor_email": "(61) 99629-4979",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "SILVIA RODRIGUES DOS SANTOS RESENDE",
    "secretario_nome": "586.645.561-72",
    "secretario_cpf": "sill.via@hotmail.com",
    "secretario_email": "(61) 99662-7331",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "2024",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52048349",
    "nome": "CMEB Professora Ilka Meireles de Matos",
    "codigo_inep": "52048349",
    "endereco": "Rua 13 - PRAÇA DA AMÉRICA - PARQUE SOL NASCENTE - LUZIÂNIA/GO - CEP: 72.855-813",
    "logradouro": "Rua 13",
    "complemento": "PRAÇA DA AMÉRICA",
    "bairro": "PARQUE SOL NASCENTE",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.855-813",
    "latitude": "-16.180043",
    "longitude": "-47.935434",
    "contato": "(61) 99133-8777",
    "email": "ilkameireles@educacao.luziania.go.gov.br",
    "gestor_nome": "723.801.361-49",
    "gestor_cpf": "daniellecv.advogada@gmail.com",
    "gestor_email": "(61) 98534-5040",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52048373",
    "nome": "CMEB Professora Joana Darc Maciel de Leles",
    "codigo_inep": "52048373",
    "endereco": "Rua Gonçalves Dias - QUADRA 79 - PARQUE ESTRELA DALVA I - LUZIÂNIA/GO - CEP: 72.804-070",
    "logradouro": "Rua Gonçalves Dias",
    "complemento": "QUADRA 79",
    "bairro": "PARQUE ESTRELA DALVA I",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.804-070",
    "latitude": "-16.252363",
    "longitude": "-47.930229",
    "contato": "(61) 99274-7363",
    "email": "joanadarc@educacao.luziania.go.gov.br",
    "gestor_nome": "729.727.931-53",
    "gestor_cpf": "eliakimhenrique2@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "INTEGRAL",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "1974",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52047784",
    "nome": "CMEB Professora Maria Clarice Meireles de Queiroz",
    "codigo_inep": "52047784",
    "endereco": "RUA BAHIA - AREA ESPECIAL - SETOR VIEGAS - LUZIÂNIA/GO - CEP: 72.810-560",
    "logradouro": "RUA BAHIA",
    "complemento": "AREA ESPECIAL",
    "bairro": "SETOR VIEGAS",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.810-560",
    "latitude": "-16.244236",
    "longitude": "-47.955815",
    "contato": "(61) 99216-0435",
    "email": "kennedy@educacao.luziania.go.gov.br",
    "gestor_nome": "013.400.941-00",
    "gestor_cpf": "anapaula.pcnunes@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "CÉLIA FIALHO SILVA",
    "secretario_nome": "381.096.891-91",
    "secretario_cpf": "celiafialho40@hotmail.com",
    "secretario_email": "(61) 99349-9919",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52048381",
    "nome": "CMEB Professora Marlene Flores de Araujo",
    "codigo_inep": "52048381",
    "endereco": "Rua 07 - LOTE 10 QUADRA 39 - PARQUE SANTA FE - LUZIÂNIA/GO - CEP: 72.834-160",
    "logradouro": "Rua 07",
    "complemento": "LOTE 10 QUADRA 39",
    "bairro": "PARQUE SANTA FE",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.834-160",
    "latitude": "-16.219569",
    "longitude": "-47.917476",
    "contato": "(61) 99699-2384",
    "email": "marleneflores@educacao.luziania.go.gov.br",
    "gestor_nome": "899.434.811-53",
    "gestor_cpf": "eversoninaciodemelo@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "LIVIA GOMES FEITOSA DE OLIVEIRA",
    "secretario_nome": "017.420.621-64",
    "secretario_cpf": "liviagfo@hotmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52088871",
    "nome": "CMEB Ramiro Aguiar",
    "codigo_inep": "52088871",
    "endereco": "Rua 54 - PARQUE ESTRELA DALVA VIII - LUZIÂNIA/GO - CEP: 72.837-320",
    "logradouro": "Rua 54",
    "complemento": "",
    "bairro": "PARQUE ESTRELA DALVA VIII",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.837-320",
    "latitude": "-16.265953",
    "longitude": "-47.907469",
    "contato": "(61) 99139-0374",
    "email": "ramiroaguiar@educacao.luziania.go.gov.br",
    "gestor_nome": "955.580.391-91",
    "gestor_cpf": "eliene_1978@outlook.com",
    "gestor_email": "(61) 99139-0374",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "BRENDA CARVALHO DE OLIVEIRA - MAT. 142110",
    "secretario_nome": "057.487.341-41",
    "secretario_cpf": "brendacarvalholima5@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52048357",
    "nome": "CMEB Rita Goncalves de Faria",
    "codigo_inep": "52048357",
    "endereco": "Rua Ipameri - AREA ESPECIAL - SAO CAETANO - LUZIÂNIA/GO - CEP: 72.805-120",
    "logradouro": "Rua Ipameri",
    "complemento": "AREA ESPECIAL",
    "bairro": "SAO CAETANO",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.805-120",
    "latitude": "-16.26315",
    "longitude": "-47.94034",
    "contato": "(61) 99551-7730",
    "email": "ritagoncalves@educacao.luziania.go.gov.br",
    "gestor_nome": "973.213.971-49",
    "gestor_cpf": "sirlenecadu@hotmail.com",
    "gestor_email": "(61) 99687-0465",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52111792",
    "nome": "CMEB Sao Mateus",
    "codigo_inep": "52111792",
    "endereco": "Rua Doutor Kisleu Dias Maciel - ROSARIO - LUZIÂNIA/GO - CEP: 72.812-135",
    "logradouro": "Rua Doutor Kisleu Dias Maciel",
    "complemento": "",
    "bairro": "ROSARIO",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.812-135",
    "latitude": "-16.24624",
    "longitude": "-47.94936",
    "contato": "(61) 99916-4072",
    "email": "saomateus@educacao.luziania.go.gov.br",
    "gestor_nome": "694.914.611-68",
    "gestor_cpf": "cristianefreitas.vital@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "VANESSA REGINA ALBANO SANTOS - MAT.142016",
    "secretario_nome": "703.592.162-18",
    "secretario_cpf": "vanessanana18236029@gmail.com",
    "secretario_email": "(61) 99518-0405",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Privada",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52048896",
    "nome": "CMEB Silas Santos Junior",
    "codigo_inep": "52048896",
    "endereco": "Avenida 02 - VILA GUARA - LUZIÂNIA/GO - CEP: 72.835-370",
    "logradouro": "Avenida 02",
    "complemento": "",
    "bairro": "VILA GUARA",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.835-370",
    "latitude": "-16.221627",
    "longitude": "-47.909617",
    "contato": "(61) 3620-1531",
    "email": "silassantos@educacao.luziania.go.gov.br",
    "gestor_nome": "025.061.701-38",
    "gestor_cpf": "silassantos@educacao.luziania.go.gov.br",
    "gestor_email": "(61) 99825-6621",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "LUCAS SABOIA TORRES",
    "secretario_nome": "019.458.611-18",
    "secretario_cpf": "silassantosjunior@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEB",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52105601",
    "nome": "CMEI Antonio Sebastiao da Silva",
    "codigo_inep": "52105601",
    "endereco": "AV GOVERNADOR JOSE FELICIANO FERREIRA, Q CM LOTE 03. JARDIM INGA. - JARDIM DO INGA - LUZIÂNIA/GO - CEP: 72.850-310",
    "logradouro": "AV GOVERNADOR JOSE FELICIANO FERREIRA, Q CM LOTE 03. JARDIM INGA.",
    "complemento": "",
    "bairro": "JARDIM DO INGA",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.850-310",
    "latitude": "-16.142080",
    "longitude": "-47.963198",
    "contato": "(61) 99279-5740",
    "email": "antoniosebastiao@educacao.luziania.go.gov",
    "gestor_nome": "900.666.181-34",
    "gestor_cpf": "liliadeazevedo@gmail.com",
    "gestor_email": "(61) 98453-9367",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52188523",
    "nome": "CMEI Carlinda Rosa de Barros Machado",
    "codigo_inep": "52188523",
    "endereco": "Rua 10 Quadra 2 Lote J - PARQUE INDUSTRIAL MINGONE - LUZIÂNIA/GO - CEP: 72.855-002",
    "logradouro": "Rua 10 Quadra 2 Lote J",
    "complemento": "",
    "bairro": "PARQUE INDUSTRIAL MINGONE",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.855-002",
    "latitude": "-16.156363",
    "longitude": "-47.938401",
    "contato": "(61) 98188-5858",
    "email": "carlindarosa@educacao.luziania.go.gov.br",
    "gestor_nome": "971.938.601-00",
    "gestor_cpf": "gekaas@hotmail.com",
    "gestor_email": "(61) 99461-2280",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52105580",
    "nome": "CMEI Celia dos Santos de Oliveira de Jesus",
    "codigo_inep": "52105580",
    "endereco": "RUA GASPER LIBERO, QUADRA 60 LOTE A/14. - JARDIM DO INGA - LUZIÂNIA/GO - CEP: 72.850-250",
    "logradouro": "RUA GASPER LIBERO, QUADRA 60 LOTE A/14.",
    "complemento": "",
    "bairro": "JARDIM DO INGA",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.850-250",
    "latitude": "-16.146780",
    "longitude": "-47.953515",
    "contato": "(61) 99279-2673",
    "email": "celiasantos@educacao.luziania.go.gov.br",
    "gestor_nome": "725.719.691-53",
    "gestor_cpf": "juceliaerafael@hotmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52095541",
    "nome": "CMEI Claudia Rosa Gomes Peixoto",
    "codigo_inep": "52095541",
    "endereco": "Quadra 260 - RUA 13 - PARQUE ESTRELA DALVA V - LUZIÂNIA/GO - CEP: 72.821-165",
    "logradouro": "Quadra 260",
    "complemento": "RUA 13",
    "bairro": "PARQUE ESTRELA DALVA V",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.821-165",
    "latitude": "-16.257856",
    "longitude": "-47.909042",
    "contato": "(61) 99278-3374",
    "email": "claudiarosa@educacao.luziania.go.gov.br",
    "gestor_nome": "903.026.801-87",
    "gestor_cpf": "marcialleles@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "ANA PAULA AIRES CARDOSO",
    "secretario_nome": "899.403.501-04",
    "secretario_cpf": "ana.revisora83@yahoo.com.br",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "2025",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52098230",
    "nome": "CMEI Debora Gomes de Azeredo",
    "codigo_inep": "52098230",
    "endereco": "RUA MOCOCA QUADRA 35 LOTE 15/17, 15/17 JARDIM ZULEIKA. - JARDIM ZULEIKA - LUZIÂNIA/GO - CEP: 72.850-635",
    "logradouro": "RUA MOCOCA QUADRA 35 LOTE 15/17, 15/17 JARDIM ZULEIKA.",
    "complemento": "",
    "bairro": "JARDIM ZULEIKA",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.850-635",
    "latitude": "-16.132940",
    "longitude": "-47.964430",
    "contato": "(61) 98345-8381",
    "email": "deboragomes@educacao.luziania.go.gov.br",
    "gestor_nome": "024.172.171-71",
    "gestor_cpf": "angelicatuka7@hotmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "2025",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52103200",
    "nome": "CMEI Dona Luzia Pereira dos Santos",
    "codigo_inep": "52103200",
    "endereco": "RUA LUIZ JARDIM, Q. 29. JARDIM BRASILIA SUL. - JARDIM BRASILIA SUL - LUZIÂNIA/GO - CEP: 72.823-250",
    "logradouro": "RUA LUIZ JARDIM, Q. 29. JARDIM BRASILIA SUL.",
    "complemento": "",
    "bairro": "JARDIM BRASILIA SUL",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.823-250",
    "latitude": "-16.248177",
    "longitude": "-47.895871",
    "contato": "(61) 99281-3150",
    "email": "donaluzia@educacao.luziania.go.gov.br",
    "gestor_nome": "965.674.811-53",
    "gestor_cpf": "sandraneves1982@gmail.com",
    "gestor_email": "(61) 9927-8168",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52082415",
    "nome": "CMEI Dona Nenzica",
    "codigo_inep": "52082415",
    "endereco": "Rua São Benedito - CENTRO - LUZIÂNIA/GO - CEP: 72.812-090",
    "logradouro": "Rua São Benedito",
    "complemento": "",
    "bairro": "CENTRO",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.812-090",
    "latitude": "-16.251834",
    "longitude": "-47.949962",
    "contato": "(61) 99275-6413",
    "email": "donanenzica@educacao.luziania.go.gov.br",
    "gestor_nome": "007.120.161-04",
    "gestor_cpf": "michelly.leal14@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "ADRIANA RODRIGUES DE FREITAS MORAIS",
    "secretario_nome": "929.686.001-68",
    "secretario_cpf": "adrianarfmorais13@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52107094",
    "nome": "CMEI Espedita Furtado Vieira",
    "codigo_inep": "52107094",
    "endereco": "Praça 04 - AV 05 - PARQUE INDUSTRIAL MINGONE II - LUZIÂNIA/GO - CEP: 72.855-245",
    "logradouro": "Praça 04",
    "complemento": "AV 05",
    "bairro": "PARQUE INDUSTRIAL MINGONE II",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.855-245",
    "latitude": "-16.146147",
    "longitude": "-47.939455",
    "contato": "(61) 99114-0323",
    "email": "espeditafurtado@educacao.luziania.go.gov.br",
    "gestor_nome": "317.056.771-34",
    "gestor_cpf": "celiamariagm@hotmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52088880",
    "nome": "CMEI Ivo Julio Meireles",
    "codigo_inep": "52088880",
    "endereco": "Avenida Gilberto Freire - QUADRA 190/203 - PARQUE ESTRELA DALVA III - LUZIÂNIA/GO - CEP: 72.831-170",
    "logradouro": "Avenida Gilberto Freire",
    "complemento": "QUADRA 190/203",
    "bairro": "PARQUE ESTRELA DALVA III",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.831-170",
    "latitude": "-16.237290",
    "longitude": "-47.909328",
    "contato": "(61) 99278-1308",
    "email": "ivojulio@educacao.luziania.go.gov.br",
    "gestor_nome": "700.952.481-53",
    "gestor_cpf": "nanda.morena.2@hotmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "MARIA GABRIELA DA SILVA BARBOSA",
    "secretario_nome": "055.511.891-63",
    "secretario_cpf": "mariagabrieladsb97@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52086127",
    "nome": "CMEI Jardim do Eden",
    "codigo_inep": "52086127",
    "endereco": "Avenida Doutor Neylon Rolim - Quadra 70, lote 26 - PARQUE ALVORADA I - LUZIÂNIA/GO - CEP: 72.836-330",
    "logradouro": "Avenida Doutor Neylon Rolim",
    "complemento": "Quadra 70, lote 26",
    "bairro": "PARQUE ALVORADA I",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.836-330",
    "latitude": "-16.213360",
    "longitude": "-47.930212",
    "contato": "(61) 99280-4552",
    "email": "esc.jardimdoeden@gmail.com",
    "gestor_nome": "975.742.441-20",
    "gestor_cpf": "vieiradiane@hotmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "25",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52103196",
    "nome": "CMEI Jose Antonio da Rocha",
    "codigo_inep": "52103196",
    "endereco": "QUADRA 607 - LOTE 1 A 20 - PARQUE ESTRELA DALVA X - LUZIÂNIA/GO - CEP: 72.856-607",
    "logradouro": "QUADRA 607",
    "complemento": "LOTE 1 A 20",
    "bairro": "PARQUE ESTRELA DALVA X",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.856-607",
    "latitude": "-16.172891",
    "longitude": "-47.960204",
    "contato": "(61) 99198-2202",
    "email": "antoniodarocha@educacao.luziania.go.gov.br",
    "gestor_nome": "014.203.711-77",
    "gestor_cpf": "karinagomes1501@yahoo.com.br",
    "gestor_email": "(61) 99198-2202",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "NATHALIA CASSIMIRO PESSOA",
    "secretario_nome": "083.405.201-64",
    "secretario_cpf": "nathalia.csmr@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52097021",
    "nome": "CMEI Lourdes Salomao",
    "codigo_inep": "52097021",
    "endereco": "RUA 18 - QUADRA.57 LOTE.12D - PARQUE JK - LUZIÂNIA/GO - CEP: 72.815-590",
    "logradouro": "RUA 18",
    "complemento": "QUADRA.57 LOTE.12D",
    "bairro": "PARQUE JK",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.815-590",
    "latitude": "-16.237074",
    "longitude": "-47.941287",
    "contato": "(61) 99838-8406",
    "email": "lourdessalomao@educacao.luziania.go.gov.br",
    "gestor_nome": "003.643.051-00",
    "gestor_cpf": "kellerorizls00@gmail.com",
    "gestor_email": "(61) 99838-8406",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "IANARA MORAIS SOUSA",
    "secretario_nome": "010.274.651-61",
    "secretario_cpf": "sousaianara@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52107949",
    "nome": "CMEI Luiza Velôso Falcão",
    "codigo_inep": "52107949",
    "endereco": "AVENIDA 03 PRAÇA 03, QUADRA 400 - ÁREA ESPECIAL - PARQUE INDUSTRIAL MINGONE II - LUZIÂNIA/GO - CEP: 72.859-400",
    "logradouro": "AVENIDA 03 PRAÇA 03, QUADRA 400",
    "complemento": "ÁREA ESPECIAL",
    "bairro": "PARQUE INDUSTRIAL MINGONE II",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.859-400",
    "latitude": "-16.152329",
    "longitude": "-47.933294",
    "contato": "(61) 99275-3874",
    "email": "luizaveloso@educacao.luziania.go.gov.br",
    "gestor_nome": "910.162.071-15",
    "gestor_cpf": "leiasantiago2008@hotmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "BIANCA DOS SANTOS CAMPOS",
    "secretario_nome": "049.576.121-45",
    "secretario_cpf": "byankkampos@gmail.com",
    "secretario_email": "(61) 99171-6104",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52083586",
    "nome": "CMEI Patricia Prado Monteiro Seixo de Brito",
    "codigo_inep": "52083586",
    "endereco": "Alameda Santa Maria - SETOR FUMAL - LUZIÂNIA/GO - CEP: 72.801-730",
    "logradouro": "Alameda Santa Maria",
    "complemento": "",
    "bairro": "SETOR FUMAL",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.801-730",
    "latitude": "-16.267356",
    "longitude": "-47.956895",
    "contato": "(61) 98120-5284",
    "email": "patriciaprado@educacao.luziania.go.gov.br",
    "gestor_nome": "989.982.851-34",
    "gestor_cpf": "paola.gomes.santos@gmail.com",
    "gestor_email": "(61) 8279-0192|(61) 8120-5284|(61) 8243-3321",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "VINICIUS NORBERTO DA COSTA SOARES",
    "secretario_nome": "080.404.051-65",
    "secretario_cpf": "vinidevfull@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52108783",
    "nome": "CMEI Perola Meirelles de Brito",
    "codigo_inep": "52108783",
    "endereco": "Rua Ademar Simão Vieira - AREA ESPECIAL - SETOR LESTE - LUZIÂNIA/GO - CEP: 72.803-550",
    "logradouro": "Rua Ademar Simão Vieira",
    "complemento": "AREA ESPECIAL",
    "bairro": "SETOR LESTE",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.803-550",
    "latitude": "-16.257015",
    "longitude": "-47.931154",
    "contato": "(61) 99975-6243",
    "email": "perolameirelles@educacao.luziania.go.gov.br",
    "gestor_nome": "010.836.253-14",
    "gestor_cpf": "cleujane@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "ILMA APARECIDA DOS REIS",
    "secretario_nome": "499.845.001-87",
    "secretario_cpf": "cristalreis@hotmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "MARIA EDUARDA RODRIGUES DOS SANTOS",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "2024",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52096866",
    "nome": "CMEI Professora Aglaia Lima Costa",
    "codigo_inep": "52096866",
    "endereco": "RUA 29, QUADRA 37 LOTE 10. - SETOR MANDU II - LUZIÂNIA/GO - CEP: 72.814-690",
    "logradouro": "RUA 29, QUADRA 37 LOTE 10.",
    "complemento": "",
    "bairro": "SETOR MANDU II",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.814-690",
    "latitude": "-16.246457",
    "longitude": "-47.927147",
    "contato": "(61) 99812-1260",
    "email": "aglaia@educacao.luziania.go.gov.br",
    "gestor_nome": "644.177.861-00",
    "gestor_cpf": "alessandralisboa2007@hotmail.com",
    "gestor_email": "(61) 99812-1260",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "INTEGRAL",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "2025",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52121216",
    "nome": "CMEI Professora Lydia Heringer Emerick",
    "codigo_inep": "52121216",
    "endereco": "Rua João Gonçalves - quadra 83 - SETOR FUMAL - LUZIÂNIA/GO - CEP: 72.801-560",
    "logradouro": "Rua João Gonçalves",
    "complemento": "quadra 83",
    "bairro": "SETOR FUMAL",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.801-560",
    "latitude": "-16.263727",
    "longitude": "-47.953958",
    "contato": "(61) 99277-3351",
    "email": "lydiaemerick@educacao.luziania.go.gov.br",
    "gestor_nome": "952.497.451-72",
    "gestor_cpf": "lucineidemeirelesbueno@gmail.com",
    "gestor_email": "(61) 99821-6508",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "INTEGRAL",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "2024",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52105717",
    "nome": "CMEI Professora Nelia de Almeida Rodrigues",
    "codigo_inep": "52105717",
    "endereco": "RUA CECILIA MEIRELES - AREA ESPECIAL - PARQUE ESTRELA DALVA I - LUZIÂNIA/GO - CEP: 72.820-140",
    "logradouro": "RUA CECILIA MEIRELES",
    "complemento": "AREA ESPECIAL",
    "bairro": "PARQUE ESTRELA DALVA I",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.820-140",
    "latitude": "-16.252405",
    "longitude": "-47.904245",
    "contato": "(61) 99840-5470",
    "email": "neliadealmeida@educacao.luziania.go.gov.br",
    "gestor_nome": "Não Informado",
    "gestor_cpf": "",
    "gestor_email": "",
    "gestor_telefone": "(61) 99840-5470",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52107086",
    "nome": "CMEI Professora Nilza Ribeiro Queiroz",
    "codigo_inep": "52107086",
    "endereco": "Avenida Jorge Lage Moura - JARDIM DO INGA - LUZIÂNIA/GO - CEP: 72.851-010",
    "logradouro": "Avenida Jorge Lage Moura",
    "complemento": "",
    "bairro": "JARDIM DO INGA",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.851-010",
    "latitude": "-16.138827",
    "longitude": "-47.948797",
    "contato": "(61) 99549-7090",
    "email": "nilzaribeiro@educacao.luziania.go.gov.br",
    "gestor_nome": "009.931.141-05",
    "gestor_cpf": "nathaschacassimiro@yahoo.com.br",
    "gestor_email": "(61) 9243-2977",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52108899",
    "nome": "CMEI Professora Valeria Dias",
    "codigo_inep": "52108899",
    "endereco": "Rua Epaminondas Roriz - JARDIM DO INGA - LUZIÂNIA/GO - CEP: 72.850-160",
    "logradouro": "Rua Epaminondas Roriz",
    "complemento": "",
    "bairro": "JARDIM DO INGA",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.850-160",
    "latitude": "-16.138616",
    "longitude": "-47.952842",
    "contato": "(61) 99175-2659",
    "email": "valeriadias@educacao.luziania.go.gov.br",
    "gestor_nome": "617.526.651-04",
    "gestor_cpf": "osmildafirmo@hotmail.com",
    "gestor_email": "(61) 99175-2659",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "SIBELE PEREIRA DA SILVA",
    "secretario_nome": "069.016.936-13",
    "secretario_cpf": "sibsilva2014@gmail.com",
    "secretario_email": "(61) 99962-2905",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52108775",
    "nome": "CMEI Professora Zilda Dias",
    "codigo_inep": "52108775",
    "endereco": "Rua 37 Quadra 26 Lote 1 - Área Especial - RESIDENCIAL ALTO DAS CARAIBAS - LUZIÂNIA/GO - CEP: 72.813-350",
    "logradouro": "Rua 37 Quadra 26 Lote 1",
    "complemento": "Área Especial",
    "bairro": "RESIDENCIAL ALTO DAS CARAIBAS",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.813-350",
    "latitude": "-16.236277",
    "longitude": "-47.950175",
    "contato": "(61) 99261-3321",
    "email": "zildadias@educacao.luziania.go.gov.br",
    "gestor_nome": "715.293.141-00",
    "gestor_cpf": "marcellarfps@gmail.com",
    "gestor_email": "(61) 99261-3321",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "VITORIA HELLEN PAIVA FERREIRA",
    "secretario_nome": "072.583.061-10",
    "secretario_cpf": "vickhellen738@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52110370",
    "nome": "CMEI Willians Vieira da Silva",
    "codigo_inep": "52110370",
    "endereco": "Rua Dr. Ary Albuquerque Qd 73 Lote 02/03 - JARDIM DO INGA - LUZIÂNIA/GO - CEP: 72.850-280",
    "logradouro": "Rua Dr. Ary Albuquerque Qd 73 Lote 02/03",
    "complemento": "",
    "bairro": "JARDIM DO INGA",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.850-280",
    "latitude": "-16.145548",
    "longitude": "-47.956910",
    "contato": "(61) 99246-9115",
    "email": "williansvieira@educacao.luziania.go.gov.br",
    "gestor_nome": "695.564.231-68",
    "gestor_cpf": "marcelebotelho77@gmail.com",
    "gestor_email": "(61) 98100-7373",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "PROFESSOR",
    "secretario_nome": "",
    "secretario_cpf": "",
    "secretario_email": "",
    "secretario_telefone": "",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52069940",
    "nome": "EMEE Eugenia Campos Coelho",
    "codigo_inep": "52069940",
    "endereco": "Rodovia Braluz - KM 03 - ZONAS RURAL - LUZIÂNIA/GO - CEP: 72.801-360",
    "logradouro": "Rodovia Braluz",
    "complemento": "KM 03",
    "bairro": "ZONAS RURAL",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.801-360",
    "latitude": "-16.284968",
    "longitude": "-47.958849",
    "contato": "(61) 99562-3802",
    "email": "eugeniacampos@educacao.luziania.go.gov.br",
    "gestor_nome": "793.831.141-34",
    "gestor_cpf": "sheilanmota@gmail.com",
    "gestor_email": "(61) 99356-5191",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "ADRIANA MEIRELES BRAZ",
    "secretario_nome": "031.447.251-70",
    "secretario_cpf": "drikinhambraz@gmail.com",
    "secretario_email": "(61) 99626-2051",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "ESPECIAL",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52121011",
    "nome": "EMEE Professor Mauricio Moura da Silva",
    "codigo_inep": "52121011",
    "endereco": "Rua Formosa - Quadra 105 - JARDIM DO INGA - LUZIÂNIA/GO - CEP: 72.850-340",
    "logradouro": "Rua Formosa",
    "complemento": "Quadra 105",
    "bairro": "JARDIM DO INGA",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.850-340",
    "latitude": "-16.151338",
    "longitude": "-47.955709",
    "contato": "(61) 99426-6216",
    "email": "mauriciomoura@educacao.luziania.go.gov.br",
    "gestor_nome": "072.442.887-94",
    "gestor_cpf": "paulajanaina08@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "JONAS BRITO ROGERIO",
    "secretario_nome": "054.642.281-01",
    "secretario_cpf": "jonasbritorogerio@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "ESPECIAL",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52106101",
    "nome": "Educandário Espírita Maria de Nazaré",
    "codigo_inep": "52106101",
    "endereco": "Rua 23 Qd 272 Lote 16 - Parque e Dalva IV - PARQUE ESTRELA DALVA IV - LUZIÂNIA/GO - CEP: 72.821-225",
    "logradouro": "Rua 23 Qd 272 Lote 16",
    "complemento": "Parque e Dalva IV",
    "bairro": "PARQUE ESTRELA DALVA IV",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.821-225",
    "latitude": "-16.259954",
    "longitude": "-47.913054",
    "contato": "(61) 99126-6939",
    "email": "mariadenazare@educacao.luziania.go.gov.br",
    "gestor_nome": "895.260.151-34",
    "gestor_cpf": "clau.skarllet123@gmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "DAIANE FIALHO CHAVES",
    "secretario_nome": "004.700.551-38",
    "secretario_cpf": "donanenzica@educacao.luziania.go.gov.br",
    "secretario_email": "",
    "secretario_telefone": "APOIO ADMINISTRATIVO",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Privada",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52107221",
    "nome": "Escola Municipal de Tempo Integral Antonio Farias de Mesquita",
    "codigo_inep": "52107221",
    "endereco": "Rua 03 - QD 27 - PARQUE ALVORADA I - LUZIÂNIA/GO - CEP: 72.836-190",
    "logradouro": "Rua 03",
    "complemento": "QD 27",
    "bairro": "PARQUE ALVORADA I",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.836-190",
    "latitude": "-16.202383",
    "longitude": "-47.922061",
    "contato": "(61) 99638-2145",
    "email": "antoniomesquita@educacao.luziania.go.gov.br",
    "gestor_nome": "811.104.641-34",
    "gestor_cpf": "veraemar@hotmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "VIVIANY REIS ESTEVES CAETANO",
    "secretario_nome": "014.547.461-57",
    "secretario_cpf": "vivianyesteves@gmail.com",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "INTEGRAL",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "2022",
    "rede": "Municipal",
    "tipo_localizacao": "Urbana",
    "turnos": "Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  },
  {
    "id": "e-52111733",
    "nome": "Instituto de Educacao Crista Estrela de Belem",
    "codigo_inep": "52111733",
    "endereco": "Avenida Kisleu Dias Maciel Quadra 153 Lote 17/18 - PARQUE ESTRELA DALVA II - LUZIÂNIA/GO - CEP: 72.820-210",
    "logradouro": "Avenida Kisleu Dias Maciel Quadra 153 Lote 17/18",
    "complemento": "",
    "bairro": "PARQUE ESTRELA DALVA II",
    "cidade": "LUZIÂNIA",
    "uf": "GO",
    "cep": "72.820-210",
    "latitude": "-16.248095",
    "longitude": "-47.910551",
    "contato": "(61) 3246-3281",
    "email": "institutoestrelabelem@gmail.com",
    "gestor_nome": "982.409.271-49",
    "gestor_cpf": "lady-pinheiro@hotmail.com",
    "gestor_email": "",
    "gestor_telefone": "PROFESSOR",
    "gestor_cargo": "ELIZA PESSOA DE CARVALHO NETA",
    "secretario_nome": "955.587.991-53",
    "secretario_cpf": "lizapessoa@yahoo.com.br",
    "secretario_email": "",
    "secretario_telefone": "AGENTE DE EDUCAÇÃO",
    "secretario_cargo": "",
    "classificacao": "CMEI",
    "tipo_unidade": "Unidade Escolar",
    "ano_funcionamento": "",
    "rede": "Privada",
    "tipo_localizacao": "Urbana",
    "turnos": "Matutino/Manhã|Vespertino/Tarde|Integral",
    "status_processo": "nao_iniciado",
    "data_inicio_escolha": "2025-12-19T13:00:00-03:00"
  }
];

export const INITIAL_PROFESSORES = [
  {
    id: 'p1111111-1111-1111-1111-111111111111',
    escola_id: 'e-52101894',
    nome: 'Ana Clara de Oliveira',
    cpf: '111.222.333-44',
    data_nascimento: '1985-04-12',
    data_admissao: '2012-02-01',
    carga_horaria: 40,
    tipo_vinculo: 'efetivo',
    faltas_injustificadas_2025: 0,
    frequencia_alfamais_percentual: 95.0,
    status_validacao: 'validado',
    justificativa_validacao: 'Documentação conferida e validada pelo gestor.',
    regencias: [
      { tipo: 'efetivo_rede', carga_horaria: 40, dias_trabalhados: 3650 }, // 10 anos x 28 = 280
      { tipo: 'efetivo_unidade', carga_horaria: 40, dias_trabalhados: 1825 } // 5 anos x 16 = 80
    ],
    publicacoes: [
      { tipo: 'livro_isbn', titulo: 'Metodologias Ativas nos Anos Iniciais (ISBN 978-85-12345)' } // 200 pts
    ],
    formacoes: [
      { tipo: 'lato_sensu', nome_curso: 'Especialização em Alfabetização e Letramento', carga_horaria: 400, modalidade: 'presencial' }, // 50 pts
      { tipo: 'alfamais', nome_curso: 'Curso de Formação Continuada AlfaMais 2025', carga_horaria: 60, modalidade: 'presencial' }, // 120 pts
      { tipo: 'sintego', nome_curso: 'Seminário de Educação Inclusiva SINTEGO', carga_horaria: 20, modalidade: 'presencial' } // 100 pts
    ],
    avaliacoes: [
      { ano: 2025, percentual: 95.5 }
    ]
  },
  {
    id: 'p2222222-2222-2222-2222-222222222222',
    escola_id: 'e-52101894',
    nome: 'Roberto Carlos da Silva',
    cpf: '222.333.444-55',
    data_nascimento: '1980-11-25',
    data_admissao: '2010-03-15',
    carga_horaria: 40,
    tipo_vinculo: 'efetivo',
    faltas_injustificadas_2025: 0,
    frequencia_alfamais_percentual: 85.0,
    status_validacao: 'validado',
    justificativa_validacao: 'Pontuação conferida.',
    regencias: [
      { tipo: 'efetivo_rede', carga_horaria: 40, dias_trabalhados: 4380 }, // 12 anos x 28 = 336
      { tipo: 'efetivo_unidade', carga_horaria: 40, dias_trabalhados: 2190 } // 6 anos x 16 = 96
    ],
    publicacoes: [
      { tipo: 'artigo_issn', titulo: 'Práticas Pedagógicas na Educação Infantil (ISSN 1234-5678)' } // 100 pts
    ],
    formacoes: [
      { tipo: 'mestrado', nome_curso: 'Mestrado em Educação e Sociedade', carga_horaria: 1200, modalidade: 'presencial' }, // 200 pts
      { tipo: 'ed_infantil_presencial', nome_curso: 'Curso de Extensão em Ed. Infantil SMEL', carga_horaria: 50, modalidade: 'presencial' } // 100 pts
    ],
    avaliacoes: [
      { ano: 2025, percentual: 90.0 }
    ]
  },
  {
    id: 'p3333333-3333-3333-3333-333333333333',
    escola_id: 'e-52101894',
    nome: 'Fernanda Souza Lima',
    cpf: '333.444.555-66',
    data_nascimento: '1992-08-30',
    data_admissao: '2018-08-10',
    carga_horaria: 30,
    tipo_vinculo: 'efetivo',
    faltas_injustificadas_2025: 0,
    frequencia_alfamais_percentual: 92.5,
    status_validacao: 'validado',
    justificativa_validacao: 'Validado com comprovantes anexados.',
    regencias: [
      { tipo: 'efetivo_rede', carga_horaria: 30, dias_trabalhados: 2190 }, // 6 anos x 16 = 96
      { tipo: 'efetivo_unidade', carga_horaria: 30, dias_trabalhados: 1095 } // 3 anos x 10 = 30
    ],
    publicacoes: [
      { tipo: 'tecnica_pedagogica', titulo: 'Projeto Feira de Ciências e Robótica' } // 50 pts
    ],
    formacoes: [
      { tipo: 'lato_sensu', nome_curso: 'Especialização em Gestão Escolar', carga_horaria: 360, modalidade: 'presencial' }, // 50 pts
      { tipo: 'alfamais', nome_curso: 'Formação AlfaMais Módulo I', carga_horaria: 40, modalidade: 'presencial' } // 80 pts
    ],
    avaliacoes: [
      { ano: 2025, percentual: 88.0 }
    ]
  },
  {
    id: 'p4444444-4444-4444-4444-444444444444',
    escola_id: 'e-52101894',
    nome: 'João Pedro Ferreira',
    cpf: '444.555.666-77',
    data_nascimento: '1995-01-05',
    data_admissao: '2021-02-15',
    carga_horaria: 20,
    tipo_vinculo: 'contrato_temporario',
    faltas_injustificadas_2025: 0,
    frequencia_alfamais_percentual: 91.0,
    status_validacao: 'validado',
    justificativa_validacao: 'Contrato temporário checado.',
    regencias: [
      { tipo: 'contrato_temporario', carga_horaria: 20, dias_trabalhados: 1095 } // 3 anos x 3 = 9
    ],
    publicacoes: [],
    formacoes: [
      { tipo: 'alfabetizacao_presencial', nome_curso: 'Curso de Alfabetização SMEL', carga_horaria: 60, modalidade: 'presencial' } // 120 pts
    ],
    avaliacoes: [
      { ano: 2025, percentual: 85.0 }
    ]
  }
];

export const INITIAL_TURMAS = [
  {
    id: 't1111111-1111-1111-1111-111111111111',
    escola_id: 'e-52101894',
    descricao: 'Pré I - Turma A',
    turno: 'matutino',
    tipo: 'pre_i',
    eh_alfamais: true,
    ano_letivo: 2026,
    status: 'ocupada'
  },
  {
    id: 't2222222-2222-2222-2222-222222222222',
    escola_id: 'e-52101894',
    descricao: '1º Ano - Turma B',
    turno: 'matutino',
    tipo: '1_ano',
    eh_alfamais: true,
    ano_letivo: 2026,
    status: 'disponivel'
  },
  {
    id: 't3333333-3333-3333-3333-333333333333',
    escola_id: 'e-52101894',
    descricao: '2º Ano - Turma A',
    turno: 'vespertino',
    tipo: '2_ano',
    eh_alfamais: true,
    ano_letivo: 2026,
    status: 'disponivel'
  },
  {
    id: 't4444444-4444-4444-4444-444444444444',
    escola_id: 'e-52101894',
    descricao: '4º Ano - Turma C',
    turno: 'vespertino',
    tipo: '3_ano_5_ano',
    eh_alfamais: false,
    ano_letivo: 2026,
    status: 'disponivel'
  },
  {
    id: 't5555555-5555-5555-5555-555555555555',
    escola_id: 'e-52101894',
    descricao: 'EJA - Módulo I',
    turno: 'noturno',
    tipo: 'eja',
    eh_alfamais: false,
    ano_letivo: 2026,
    status: 'disponivel'
  }
];

export const INITIAL_ESCOLHAS = [
  {
    id: 'c1111111-1111-1111-1111-111111111111',
    escola_id: 'e-52101894',
    turma_id: 't1111111-1111-1111-1111-111111111111',
    professor_id: 'p1111111-1111-1111-1111-111111111111',
    ordem_classificacao: 1,
    turno_selecionado: 'matutino',
    status: 'confirmada',
    data_escolha: '2025-12-19T13:15:00-03:00'
  }
];

export const INITIAL_LOGS = [
  {
    id: 'l1111111-1111-1111-1111-111111111111',
    usuario_nome: 'Profa. Maria das Graças Silva',
    usuario_perfil: 'gestor',
    acao: 'Confirmação de Escolha de Turma',
    detalhes: { professor: 'Ana Clara de Oliveira', turma: 'Pré I - Turma A', turno: 'matutino' },
    ip: '189.120.45.12',
    timestamp: new Date().toISOString()
  },
  {
    id: 'l2222222-2222-2222-2222-222222222222',
    usuario_nome: 'Administrador SME',
    usuario_perfil: 'administrador',
    acao: 'Atualização de Horário do Processo',
    detalhes: { escola: 'Escola Municipal JK', data_inicio: '19/12/2025 13:00' },
    ip: '201.54.122.90',
    timestamp: new Date(Date.now() - 3600000).toISOString()
  },
  {
    id: 'l3333333-3333-3333-3333-333333333333',
    usuario_nome: 'Técnico de Suporte SME',
    usuario_perfil: 'tecnico',
    acao: 'Validação de Sistema de Auditoria',
    detalhes: { acao: 'Exportação de relatórios em CSV habilitada' },
    ip: '127.0.0.1',
    timestamp: new Date(Date.now() - 7200000).toISOString()
  }
];
